# Site settings
title: "Hasan's Notes"
description: "Personal knowledge repository - Physics, Philosophy, Science, and more. "
author: "Hasan"
baseurl: ""
url: "https://hhshanto.github.io"

# Build settings
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# Collections - organizing different types of content
collections:
  physics:
    output: true
    permalink: /physics/:title/
  philosophy:
    output: true
    permalink: /philosophy/:title/
  science:
    output: true
    permalink: /science/:title/
  misc:
    output: true
    permalink: /misc/:title/